# Generated by Django 4.1.2 on 2022-11-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_compilermodel_fail_compilermodel_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilermodel',
            name='num',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
