# Generated by Django 4.1.2 on 2022-11-22 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0003_compilermodel_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compilermodel',
            name='num',
        ),
    ]
